### ISSUE TITLE
RFC: page editor field data type toggle

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1020]
**Context**
- Some bricks accept number/boolean/`null` values
- Template expressions (mustache, nunjucks) produce a string
- The `v1` behavior is to convert a variable name to its value if the variable is available. (Yes, this behavior is terrible)
- If the user touches a field, it becomes a string instead of null leading. This is fragile, because `""` is generally not a valid/meaningful input for bricks
- Current workaround is to use a `jq` brick to create a JQ object by including a template in the value of a property, e.g., `{ value: {{ numberVar }} }` 

**Some Idea**
- Automatically cast to the required type (bad idea, this is how the world got wacky JS conversion behavior)
- If a field supports multiple types, allow the user to toggle between "template expression entry" vs. literal number/boolean/null entry. (This won't solve the implicit variable usage issues)
- When using the expression entry mode, also allow the user to indicate that the value should be converted to the given type?

**Comment by twschiller** [comment]
My current thinking for the approach 

In YAML, we'll use tags to identify how the expression should be evaluated: https://yaml.org/spec/1.2.1/

```yaml
# interpreted as a variable path - should we do null/optional coalescing by default?
bar: !var "@input.bar"
foo: !mustache "Will be interpreted as a mustache template: {{ first_name }}"
baz: !nunjucks "Will be interpreted as a Nunjucks template: {{ first_name | capitalize}}"
# interpreted as a JQ filter that's passed the context
quox: !jq "if .foo then 1 else 2 end"
# recorded as usual
myNumber: 42
```

In the JS/JSON, these will be expanded in to an object:
```json
bar: {
  "__type__": "var",
  "__value__": "@input.bar"
}
```

In the Page Editor UX for block configs, for each field we'll provide a way to toggle between the expression type. The valid toggles are determined by the JSONSchema

**Open Questions**
- Do our YAML libraries (JS/Python) support these tags in a safe way?
- Should we provide a way to cast string values produced from template expressions? This is mostly mostly useful for writing conditionals (which are very verbose in those template languages)

**Other Considerations**
- This will need to use `manifestVersion: 2` in brick definitions
