### ISSUE TITLE
Add support for calling remote bricks

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1202]
**Context**
- In https://github.com/pixiebrix/pixiebrix-app/issues/307 we're adding support for server bricks

**Implementation Sketch**
- Add a "remote" window: http://github.com/pixiebrix/pixiebrix-extension/blob/12eb12a39e8ca496763b4b7d5f52cbf793ec2d45/src/blocks/types.ts#L48-L48
- Add a case to handle the server window: http://github.com/pixiebrix/pixiebrix-extension/blob/12eb12a39e8ca496763b4b7d5f52cbf793ec2d45/src/blocks/combinators.ts#L217-L217
- Define an `executeOnServer` method in executor.ts that calls the endpoint defined in https://github.com/pixiebrix/pixiebrix-app/issues/307

**Other Notes**
- Use the `getLinkedApiClient` method to get an authenticated axios client: http://github.com/pixiebrix/pixiebrix-extension/blob/12eb12a39e8ca496763b4b7d5f52cbf793ec2d45/src/services/apiClient.ts#L52-L52
- The `window` directive is not exposed in the Page Editor yet, so you'll need to use it via the Workshop
- Multi-Page automation reference docs for the workshop: https://docs.pixiebrix.com/developer-guide/multi-page-automation

**Example**

Make sure you've run `python manage.py load_fixtures fixtures/contrib/` locally so you have the `@pixiebrix/context-search` extension point available locally

```yaml
apiVersion: v1
kind: recipe
metadata:
    id: remote-test
    name: Remote brick test
    version: 1.0.0
    description: Test running a brick remotely        
extensionPoints:
  - id: "@pixiebrix/context-search"
    label: Echo server
    config:
      caption: Echo
      action:
        - id: "@pixiebrix/identity"
          # Uncomment this next line to run remotely
          # window: remote
          config: 
            foo: 42
        - id: "@pixiebrix/browser/alert"
          config:
             message: "foo={{foo}}"
```
