### ISSUE TITLE
Indicate insert/selection mode on host page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1556]
TODO: decide what the indicator should look like (border?)

**Comment by fregante** [comment]
I like the idea! 

Maybe it could match the style of the overlay itself

https://user-images.githubusercontent.com/1402241/135714569-9f4b8243-0de2-4f05-8cc0-172e5627356b.mov

Demo CSS:

```css
html:not(:hover):before {
    content: '';
    border: solid 30px rgba(182, 109, 255, 0.2);
    position: fixed;
    z-index: 1000000000;
    inset: 0;
}
```
