### ISSUE TITLE
Error loading form made in 1.4.1 in version 1.4.2+

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#1684]
This was exported from the 1.4.1 page editor and errors out when 
1. loaded in the 1.4.2/1.4.3 page editor 
2. You add a field

My guess is it's caused by field1 being in the uiSchema (probably left over from a rename) and so when you add a field that field is called field1 and does have enum values/names defined for it

@BALEHOK Could you confirm that this field renaming issue has been fixed in 1.4.2 so we won't have this problem in the future going forward? (Was the renaming issue fixed in https://github.com/pixiebrix/pixiebrix-extension/pull/1648)?

![image](https://user-images.githubusercontent.com/1879821/137839157-bcc8fefd-d680-4368-87a6-c7fabdc8468b.png)

```
apiVersion: v1
kind: recipe
metadata:
  id: ""
  name: Send selected to Slack
  description: Blueprint exported from PixieBrix
  version: 1.0.0
extensionPoints:
  - id: "@pixiebrix/context-search"
    label: Send selected to Slack
    services: {}
    config:
      title: Send selected to Slack
      action:
        - id: "@pixiebrix/form-modal"
          outputKey: form
          config:
            schema:
              title: Choose channel
              type: object
              properties:
                channel:
                  name: field1
                  title: channel
                  type: string
                  enum:
                    - "#engineering"
                    - "#marketing"
                    - "#ideas"
                    - "#slack-demos"
              required:
                - channel
            uiSchema:
              ui:order:
                - channel
                - "*"
              field1:
                ui:widget: select
              channel:
                ui:widget: select
            cancelable: true
            submitCaption: Submit
        - id: slack/advanced-message
          config:
            hookUrl: >-
              https://hooks.slack.com/services/REDACTED/
            channel: "@form.channel"
            attachments:
              - text: "@input.selectionText"
                fallback: "@input.selectionText"
                pretext: "{{{@input.pageUrl}}}"
```
