### ISSUE TITLE
Can't create new private integration

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2230]
**Context**
- Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/2167?

**Steps to Reproduce**
- Click Add Private Integration
- Enter the information
- Click create
- The "Delete" button appears in the modal
- The Modal closes
- A success message is shown
- The integration configuration is not displayed in the private integration table

Here is the definition I'm using:
```
apiVersion: v1
kind: service
metadata:
  id: rapidapi/ocr-supreme
  version: 1.0.1
  name: OCR Supreme (Rapid API)
  description: Powerful optical character recognition
  url: https://ocr-supreme.p.rapidapi.com/ocr/
isAvailable:
  matchPatterns:
    - https://ocr-supreme.p.rapidapi.com/ocr/*
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    key:
      $ref: "https://app.pixiebrix.com/schemas/key#"
      description: Your RapidAPI key, x-rapidapi-key
  required:
    - key
authentication:
  headers:
    x-rapidapi-key: "{{key}}"
    x-rapidapi-host: ocr-supreme.p.rapidapi.com
```
