### ISSUE TITLE
"Package None does not exist" error when sharing quick bar blueprint

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2420]
![image](https://user-images.githubusercontent.com/1879821/149845421-5b6d8807-aa00-4c93-b5fe-e031b409228c.png)

The only thing unusual about the blueprint is that is uses the quickBar? This might be a problem with the server?

Here's the exported blueprint

```
apiVersion: v3
kind: recipe
metadata:
  id: ""
  name: Submit to Hacker News
  description: Blueprint exported from PixieBrix
  version: 1.0.0
definitions:
  extensionPoint:
    kind: extensionPoint
    definition:
      type: quickBar
      documentUrlPatterns:
        - "*://*/*"
      contexts:
        - page
      targetMode: eventTarget
      reader:
        - "@pixiebrix/document-metadata"
      isAvailable:
        matchPatterns:
          - https://news.ycombinator.com/submit
        urlPatterns: []
        selectors: []
extensionPoints:
  - id: extensionPoint
    label: Submit to Hacker News
    services: {}
    config:
      title: Submit to HN
      icon:
        id: ycombinator
        library: simple-icons
        size: 16
      action:
        - id: "@pixiebrix/form-modal"
          config:
            schema:
              title: !nunjucks Submit to HN
              type: object
              properties:
                title:
                  title: !nunjucks Title
                  type: string
                  description: !nunjucks The title of the submission
                  default: !var "@input.title"
                url:
                  title: !nunjucks URL
                  type: string
                  description: !nunjucks The URL of the submission
                  format: uri
                  default: !var "@input.url"
              required:
                - title
                - url
            uiSchema:
              ui:order:
                - title
                - url
                - "*"
            cancelable: true
            submitCaption: Submit
            location: modal
          outputKey: form
        - id: "@pixiebrix/browser/open-tab"
          config:
            spaceEncoding: plus
            url: !nunjucks https://news.ycombinator.com/submit
          label: Open HN
        - id: "@pixiebrix/form-fill"
          config:
            formSelector: form
            fieldNames:
              title: !var "@form.title"
              url: !var "@form.url"
            submit: false
          window: target
```
