### ISSUE TITLE
Brick to read all tables on a page to an object by table name

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2434]
**Context**
- https://github.com/pixiebrix/pixiebrix-extension/pull/2380 added a table parser brick
- We're trying to move toward more data extraction as "selectorless"

**Implementation Sketch**
- Find all table elements on a page
- Parse each using our approach rom #2380, producing undefined if not available
- For each table, come up with a property/field name for referring to that table

**Output Schema**
```yaml
tables:
  type: object
  additionalProperties:
      type: object
      properties:
         fieldNames:
            type: array
         records:
            type: array
```

**Discussion**
The trick is how to come up with a robust/stable property name for table. Some ideas:

- If table has `caption` tag, use that but property-name-ify it
- Use the id (if it's not a denylisted id, e.g., Vue element id)
- Use the aria-label if available, but property-name-ify it
- Follow the aria-describedby reference, and property-name-ify the caption
- Use a hash of the field names? Concatenation of the field names?
- If it has a unique class name across tables, use that?

If we can't generate a good name for a table, we can just skip it

It would be good to create this as a `generateName` method so we can use it some other places where we can generally extract information
