### ISSUE TITLE
Error thrown on Custom form submit

### ISSUE THREAD

**Issue by BALEHOK** [pixiebrix/pixiebrix-extension#2946]
Steps:
1. Add "Show a modal or sidebar form" brick.
2. Invoke the extension, fill the form and Submit.

Expected:
Form is submitted successfully, the 'data' logged to the console.

Actual:
An error is logged in the console, the `data` is undefined.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/3116723/158816594-3b0380f7-5ff2-4e26-b9e6-0054a875f240.png">

```
Error compiling schema, function code: var refVal1 = refVal[1]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;      if (rootData === undefined) rootData = data;      var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if ((typeof data === "number")) {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;
```

```
{
    "data": undefined,
    "context": {
        "extensionPointId": "@internal/de6188b5041b1f74fdd1367df93bc08cc622b9ff",
        "label": "Modal form",
        "extensionId": "1846ba01-5c00-40f2-a4b4-9baf74e999ea"
    }
}
```

Extension export YAML:
```
apiVersion: v3
kind: recipe
metadata:
  id: ""
  name: Modal form
  description: Blueprint exported from PixieBrix
  version: 1.0.0
definitions:
  extensionPoint:
    kind: extensionPoint
    definition:
      type: menuItem
      reader:
        - "@pixiebrix/document-metadata"
      isAvailable:
        matchPatterns:
          - "*://*/*"
        urlPatterns: []
        selectors: []
      containerSelector: div:has(> a:contains("Tour"))
      position: append
      template: "<a href=\"#\" style=\"color: orange\">{{{ caption }}}</a>"
extensionPoints:
  - id: extensionPoint
    label: Modal form
    services: {}
    config:
      caption: Show form
      action:
        - id: "@pixiebrix/form-modal"
          config:
            schema:
              title: Example Form
              type: object
              properties:
                example:
                  title: Example Field
                  type: string
                  description: An example form field
            uiSchema:
              ui:order:
                - example
                - "*"
            cancelable: true
            submitCaption: Submit
            location: modal
          outputKey: form
      dynamicCaption: false
```
