### ISSUE TITLE
Add managed storage to bootstrap PixieBrix link

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3064]
## Context
- Enterprises use Chrome Policy Objects to deliver the PixieBrix browser extension to end-users
- Currently, those users have to manually link their PixieBrix extension to their account
- Chromium and Firefox support managed storage for providing options to extensions: https://github.com/w3c/webextensions/issues/174#issuecomment-1062494445

## Implementation Sketch
- Add a JSON Schema for the managed storage that's bundled with the extension
- Add a managed storage entry to the manifest: https://developer.chrome.com/docs/extensions/mv2/manifest/storage/
- On extension startup, [set the base URL](http://github.com/pixiebrix/pixiebrix-extension/blob/f7a0a72e69c1ba10671257256695648af87782da/src/services/baseService.ts#L44-L44) to based on hostname in the storage (defaulting to the process.ENV value if it's not provided in the managed storage)
- In the [deployments.ts heartbeat](http://github.com/pixiebrix/pixiebrix-extension/blob/f7a0a72e69c1ba10671257256695648af87782da/src/background/deployment.ts#L330-L330) pass the campaignIds to the API

## Managed Storage Schema: 
In YAML for readability: 

```yaml
type: object
properties:
  primaryOrganizationId:
    type: string
    description: PixieBrix organization id the extension should link to
    format: uuid
  partnerId:
    type: string
    description: PixieBrix partner id
    format: uuid
  campaignIds:
    type: array
    description: Campaign ids the extension is associated with
    items:
       type: string
       format: uuid
  hostname:
    type: string
    description: PixieBrix API hostname
    default: app.pixiebrix.com
```

## Follow-up Tickets
- In [deployments.ts](http://github.com/pixiebrix/pixiebrix-extension/blob/f7a0a72e69c1ba10671257256695648af87782da/src/background/deployment.ts#L414-L414), if the primaryOrganizationId is set but the extension is not linked, open the extension linking flow
- On first run experience, query the PixieBrix API with the primaryOrganizationId and partnerId to retrieve branding and onboarding configuration
