### ISSUE TITLE
Bug: Unused extension point definitions are not removed properly from blueprints on save

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#3222]
After adding a removing a new extension a few times, the blueprint appears like this in the workshop:

_Notice the unused `extensionPoint2` and `extensionPoint3`_

```
kind: recipe
options:
  schema:
    type: object
    required:
      - color
    properties:
      color:
        type: string
        title: What is your favorite color?
        description: ''
  uiSchema:
    ui:order:
      - color
      - '*'
metadata:
  id: '@ben-loe/recipe'
  name: Recipe
  version: 1.0.3
  description: Created with the PixieBrix Page Editor
apiVersion: v3
definitions:
  extensionPoint:
    kind: extensionPoint
    definition:
      type: menuItem
      reader:
        - '@pixiebrix/document-metadata'
      position: append
      template: |-
        <button
            class="artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom org-overflow-menu__dropdown-trigger artdeco-button artdeco-button--2 artdeco-button--secondary artdeco-button--muted"
            type="button">{{{ caption }}}</button>
      isAvailable:
        selectors: []
        urlPatterns: []
        matchPatterns:
          - https://www.linkedin.com/*
      containerSelector: div:has(> button:contains("More"))
  extensionPoint2:
    kind: extensionPoint
    definition:
      type: menuItem
      reader:
        - '@pixiebrix/document-metadata'
      position: append
      template: |-
        <button
            class="artdeco-dropdown__trigger artdeco-dropdown__trigger--placement-bottom org-overflow-menu__dropdown-trigger artdeco-button artdeco-button--2 artdeco-button--secondary artdeco-button--muted"
            type="button">{{{ caption }}}</button>
      isAvailable:
        selectors: []
        urlPatterns: []
        matchPatterns:
          - https://www.linkedin.com/*
      containerSelector: div:has(> button:contains("More"))
  extensionPoint3:
    kind: extensionPoint
    definition:
      type: contextMenu
      reader:
        - '@pixiebrix/document-metadata'
      contexts:
        - all
      targetMode: eventTarget
      isAvailable:
        selectors: []
        urlPatterns: []
        matchPatterns:
          - https://www.linkedin.com/*
      documentUrlPatterns:
        - https://www.linkedin.com/*
  extensionPoint4:
    kind: extensionPoint
    definition:
      type: contextMenu
      documentUrlPatterns:
        - https://www.linkedin.com/*
      contexts:
        - all
      targetMode: eventTarget
      reader:
        - '@pixiebrix/document-metadata'
      isAvailable:
        matchPatterns:
          - https://www.linkedin.com/*
        urlPatterns: []
        selectors: []
extensionPoints:
  - label: Recipe
    config:
      action:
        - id: '@pixiebrix/browser/alert'
          config:
            type: info
            message: !nunjucks boo recipe!
            duration: 2500
      caption: Recipe
      dynamicCaption: false
    id: extensionPoint
    services: {}
  - label: recipe ctx
    config:
      title: Context menu item
      action: []
    id: extensionPoint4
    services: {}
```
