### ISSUE TITLE
The sidebar stopped loading correctly: `Cannot read properties of undefined (reading 'location')`

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4031]
Suddenly, after working on #4024 I can no longer load the sidebar. I:

- cleared the token
- did a factory reset
- did a clean `npm install`
- built from `main` (94ec14a0)
- restarted the build
- restarted the browser

but this error persists:

```
TypeError: Cannot read properties of undefined (reading 'location')
    at useLocation (sidebar.js:98476:29)
    at useRouteMatch (sidebar.js:98491:18)
    at RequireAuth (sidebar.js:114056:87)
    at renderWithHooks (sidebar.js:72804:18)
    at mountIndeterminateComponent (sidebar.js:75630:13)
    at beginWork (sidebar.js:76868:16)
    at HTMLUnknownElement.callCallback (sidebar.js:61764:14)
    at Object.invokeGuardedCallbackDev (sidebar.js:61813:16)
    at invokeGuardedCallback (sidebar.js:61875:31)
    at beginWork$1 (sidebar.js:81778:7)
```

<img width="399" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/184590279-27d90d3a-858c-4f3f-b385-d8ad824dc246.png">

The error happens in react-router’s own code, starting here:

https://github.com/pixiebrix/pixiebrix-extension/blob/f8764f54ef69f615909a2d554d9fe3b0f8d0c342/src/auth/RequireAuth.tsx#L163

Note: we're not using the latest react-router version, it's something I could look into. Using the deprecated `location` (seen here) doesn't look idiomatic for react-router

- https://github.com/pixiebrix/pixiebrix-extension/issues/1851

**Comment by fregante** [comment]
No active blueprints:

<img width="903" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/184591344-56b4fd85-487d-4ee7-a885-9038c434bc6d.png">

But this is the last extension I was working on:

```yml
apiVersion: v3
kind: recipe
metadata:
  id: ""
  name: pbx.vercel.app side panel
  description: Blueprint exported from PixieBrix
  version: 1.0.0
definitions:
  extensionPoint:
    kind: extensionPoint
    definition:
      type: actionPanel
      reader:
        - "@pixiebrix/document-metadata"
      isAvailable:
        matchPatterns:
          - "*://*/*"
        urlPatterns: []
        selectors: []
      trigger: load
      debounce:
        waitMillis: 250
        leading: false
        trailing: true
      customEvent: null
extensionPoints:
  - id: extensionPoint
    label: pbx.vercel.app side panel
    services: {}
    config:
      heading: ugh
      body:
        - id: "@pixiebrix/form"
          config:
            storage:
              type: state
              namespace: blueprint
            successMessage: Successfully submitted form
            schema:
              title: Example Form
              type: object
              properties:
                notes:
                  title: Example Notes Field
                  type: string
                  description: An example notes field
                iamge:
                  title: !nunjucks image
                  type: string
            uiSchema:
              notes:
                ui:widget: textarea
              ui:order:
                - notes
                - iamge
                - "*"
              iamge:
                ui:widget: imageCrop
                source: !nunjucks >-
                  https://cdn.pixabay.com/photo/2015/10/01/17/17/car-967387__480.png
```

**Comment by fregante** [comment]
Side note:

```yml
              image:
                ui:widget: imageCrop
                source: !nunjucks >-
```

is this normal? Why is `nunjucks` being used/reported on a `Text` field? I did not use `Variable`, I just pasted a URL
