### ISSUE TITLE
`pixiebrix/get` brick inputSchema should support non-string params

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#431]
The `pixiebrix/get` inputSchema current restricts `params` to strings. There's no reason to not support other primitive types as well e.g., numeric/boolean

Implementation sketch:
* Update inputSchema
* Ensure reasonable behavior in params generation (e.g., just run toString on the arguments). If a user needs to convert a boolean value to 0/1 they can use templating

**Comment by fregante** [comment]
This only applies to values passed via yaml, I think, but I can't find a way to import a custom yaml or edit it 

```yaml
apiVersion: v1
kind: recipe
metadata:
  id: ''
  name: My google.com button
  description: Blueprint exported from PixieBrix
  version: 1.0.0
extensionPoints:
  - id: '@fregante/google.com/foundation-2'
    label: My google.com button
    services: {}
    config:
      caption: Action
      dynamicCaption: false
      action:
        - id: '@pixiebrix/get'
          config:
            url: 'https://hookb.in/2qJz6EqKoGc9BBKG1MlV'
            params:
              property1: name
              property2: '1'
```

I only see the inline editor in the workshop, but only for the foundation, e.g.

```yaml
apiVersion: v1
kind: extensionPoint
metadata:
  id: '@fregante/google.com/foundation-2'
  version: 1.0.0
  name: google.com Button
  description: Button created with the Page Editor
definition:
  type: menuItem
  reader:
    - '@fregante/google.com/foundation-2-reader'
  isAvailable:
    matchPatterns: 'https://www.google.com/*'
  containerSelector: 'div:has(> a:contains("News"))'
  position: append
  template: |-
    <a class="hide-focus-ring"
        href="#"
        data-hveid="CAIQBg"><span class="bmaJhd iJddsb"
            style="height:16px;width:16px">{{{ icon }}}{{{ caption }}}</span></a>
```

**Comment by twschiller** [comment]
A current limitation with our visual configuration interface and page editor is there's no way to good way to introduce numeric values. (There's a hack where you use the `@pixiebrix/jq` brick)

To reproduce the problem in the issue you can, 1) "+ Create New Brick" in the workshop, 2) paste in the recipe/extension point from your comment, 3) give it a unique id, 4) change the value of property2 to the number, 5) save it, 6) go to the "Marketplace" in the sidebar and find the blueprint to activate it

```
apiVersion: v1
kind: recipe
metadata:
  id: '@fregante/google.com/demo-blueprint'
  name: My google.com button
  description: Blueprint exported from PixieBrix
  version: 1.0.0
extensionPoints:
  - id: '@fregante/google.com/foundation-2'
    label: My google.com button
    services: {}
    config:
      caption: Action
      dynamicCaption: false
      action:
        - id: '@pixiebrix/get'
          config:
            url: 'https://hookb.in/2qJz6EqKoGc9BBKG1MlV'
            params:
              property1: name
              property2: 1
```

Let me know if you're still hitting issues and I can send over a quick loom
