### ISSUE TITLE
Disable CodeCov annotations

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4355]
As seen on https://github.com/pixiebrix/pixiebrix-extension/pull/4354/files#r979474090, they distract from the code and aren't useful unless we're targeting [100% coverage](https://about.codecov.io/blog/the-case-against-100-code-coverage/) 

<img width="464" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/192259689-df39d3ae-bf08-4948-9b30-6a75a59600a7.png">

**Comment by twschiller** [comment]
Likely related to the conversation thread here: https://pixiebrix.slack.com/archives/C023KL47XV4/p1663969464189969. I think CodeCov enabled some features we didn't want when I reconnected it/upgraded our plan

**Comment by fregante** [comment]
Also:

<img width="546" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/193250672-1074b365-c44d-4f2a-a7f5-36898e81f16c.png">

**Comment by twschiller** [comment]
I just tried turning off annotations by updating our global codecov YAML: https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml

Our YAML is currently:

```yaml
github_checks:
    annotations: false
```

**Comment by fregante** [comment]
I don't see annotations anymore, which is good. I still see PRs failing due to "reduced coverage" though:

<img width="610" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/193997031-32b6ad04-42e3-4908-99ff-b64386e41cc5.png">

**Comment by twschiller** [comment]
I've also just tried disabling the patch statuses. We'll see what happens:

```
github_checks:
  annotations: false
coverage:
  status:
    patch: false
```

**Comment by fregante** [comment]
The `patch` is indeed gone, project is still there:

<img width="615" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/195795850-ee1e701c-4e94-4888-a053-446d835ec580.png">

**Comment by twschiller** [comment]
Giving this a try:

```
coverage:
  status:
    patch: false
    project:
      # https://docs.codecov.com/docs/commit-status#excluding-tests-example
      # disable the default status that measures entire project
      default: false
github_checks:
  annotations: false
```
