### ISSUE TITLE
Running brick with DB ref parameter errors at runtime with "Unresolved $ref"

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4505]
Steps to Reproduce
---
I created a brick in the workshop that uses the DB schema type for an argument
```yaml
apiVersion: v3
kind: component
metadata:
  id: "@todd/dev/test-db-param"
  name: Test DB Param
  version: 1.0.1
  description: Test brick for DB parameters
inputSchema:
  type: object
  $schema: https://json-schema.org/draft/2019-09/schema#
  required:
    - db
  properties:
    db: 
      $ref: "https://app.pixiebrix.com/schemas/database#"
pipeline:
  - id: "@pixiebrix/browser/alert"
    config:
      message: "It worked!"
```

Screenshots
---
DB selector is showing as expected
![image](https://user-images.githubusercontent.com/1879821/196813703-eeebe549-7f1d-41f9-84bb-cfc1ac27d5e1.png)

Error
![image](https://user-images.githubusercontent.com/1879821/196813800-014c7c43-b899-47c1-97bd-1d166242065c.png)

Discussion
---
- The check is performed by validateInput
- I think we need to add database schema to the addSchema calls: https://github.com/pixiebrix/pixiebrix-extension/blob/e2d635a3e883fc682372f378b76bd46b404dccd3/src/validators/generic.ts#L138-L138
