### ISSUE TITLE
Improve sidebar behavior on inflexible websites

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#4518]
Sometimes, websites have fixed widths and don't adapt well when the sidebar is injected, which usually causes content to be unreachable. This was noted in https://github.com/pixiebrix/pixiebrix-extension/pull/4285#issuecomment-1247064084 as well.

I have a possible solution for this:
```css
html {display: flex; overflow: hidden}
body {overflow-x: scroll}
.sidebar {position: sticky}
```

This makes the two views mostly independent from each other:

![gif](https://user-images.githubusercontent.com/1402241/197179991-2dfc354e-7d9a-444d-9684-4b9bccc8d2bf.gif)

Elements with `position: fixed` could also be _disabled_ via `body {transform: rotate(0.1deg)}`

These changes however would be more _invasive_ than what we currently have, so they might cause trouble on some sites, even if they fix many issues on others.
