### ISSUE TITLE
Broken field type toggle during mod activation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8519]
## Describe the bug

- Selecting `ABC` in the field type toggle during mod activation for `@pixies/template/translation` doesn't do anything
- Should `ABC` even be an option for the field given the schema type? Need to confirm the expected behavior
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1716861180646839

## To Reproduce

1. Activate `@pixies/template/translation` in the Extension Console
1. Reactivate `@pixies/template/translation` in the sidebar

## Options Schema

The field uses the oneOf const/title options formulation:

```yaml
  schema:
    type: object
    $schema: https://json-schema.org/draft/2019-09/schema#
    required:
      - defaultLanguage
    properties:
      defaultLanguage:
        type: string
        oneOf:
          - const: am
            title: 🇪🇹 Amharic
```

## Actual behavior

- Field shows a type toggle
- Selecting `ABC` does nothing and there's no error in the console

## Expected behavior

- If `ABC` is a valid option, field should switch to text entry when selected
- If `ABC` is not a valid option, it's not included in the field toggle dropdown. If there's a single valid field type, show the field toggle as disabled.
- TODO: determine expected available field type toggles for `@pixies/template/translation`
    - Should only ever be a select per @BrandonPxBx 

## Screenshots/Loom

<img width="913" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/7f3e966b-2f4e-4dcb-927b-2154dce75719">
